Update generate-clients doc dependencies
aws/aws-sdk-js-v3 pull request #2224
Opened 2021-04-08 23:23 UTC by PaulThompson

Documentation to mention dependency on smithy-typescript.

### Issue #1291 

### Description
Add link in documentation text for the dependency smithy-typescript

### Testing
The link to external dependency install steps works, as has been noted by myself and @ajredniwja

### Additional context
The dependency on smithy-typescript crosses over from the usual node/javascript package ecosystem into java/maven/gradle used by smithy.  It's also for an internal/developer step in the codebase.  As such it is not an automated install of the dependency.

---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-04-08 23:33 UTC, aws-sdk-js-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: sdk-staging-test
* Commit ID: d3e716e045f2d4ab7567311f71a83e941051df05
* Result: SUCCEEDED
* [Build Logs](https://09vzxhs6t5.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=ae83d61e-a218-4447-a98d-e955c0b68c89%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-04-08 23:34 UTC, ajredniwja reviewed
Just a small change: Can "It requires" be changed to follow "Follow steps found at: url" as it is already under prerequisites section. 

I also changed the title to follow the semantic pull request rules.

2021-04-08 23:38 UTC, aws-sdk-js-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: sdk-staging-test
* Commit ID: 55f87a377332075913e51480c76c2f7fb23a910c
* Result: SUCCEEDED
* [Build Logs](https://09vzxhs6t5.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=275c709a-b17f-4607-a9e0-edeb9655f7b5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-04-13 23:21 UTC, AllanZhengYP approved these changes

2021-04-13 23:24 UTC, AllanZhengYP commented on scripts/generate-clients/README.md
> +
```suggestion
* Node.js version >= 12.
* [Build and publish Smithy-TypeScript locally](https://github.com/awslabs/smithy-typescript#steps-to-build).

```

2021-04-13 23:25 UTC, AllanZhengYP requested changes
Thank you for the PR! The `requires` in no needed as it's already under `Prerequisite` sectioin.

2021-04-17 00:16 UTC, AllanZhengYP approved these changes

2021-04-17 00:16 UTC, merged

2021-04-17 00:25 UTC, aws-sdk-js-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: sdk-staging-test
* Commit ID: 3efee45f3ffb8e933482619edf6a0261c3a33b73
* Result: SUCCEEDED
* [Build Logs](https://09vzxhs6t5.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=1083fd58-b9ed-445e-9fdc-4a7bc453802f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-04-17 00:25 UTC, aws-sdk-js-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: sdk-staging-test
* Commit ID: 3efee45f3ffb8e933482619edf6a0261c3a33b73
* Result: SUCCEEDED
* [Build Logs](https://09vzxhs6t5.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=3c903023-779e-4fe7-ae1b-b49fecbc3733%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->