Strict date parsing regeneration
aws/aws-sdk-js-v3 pull request #2760
Opened 2021-09-07 18:31 UTC by adamthom-amzn

### Description
Regenerate clients and protocol tests with strict date parsing enabled.

### Testing
Ran the protocol tests locally.

---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-09-08 12:10 UTC, JordonPhillips approved these changes

2021-09-08 12:11 UTC, JordonPhillips requested changes

2021-09-08 12:11 UTC, JordonPhillips commented on codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsProtocolUtils.java
> +        if (!testCase.getId().matches("^RestJsonBody\\w+MalformedValueRejected.*")) {
I think you need to rebase - you're adding this back in

2021-09-08 18:13 UTC, adamthom-amzn commented
Tests are going to fail until https://github.com/awslabs/smithy-typescript/pull/416 is merged

2021-09-08 19:05 UTC, AllanZhengYP approved these changes

2021-09-09 10:34 UTC, JordonPhillips approved these changes

2021-09-09 10:34 UTC, merged