chore(deps-dev): bump jest to 28.1.1
aws/aws-sdk-js-v3 pull request #3732
Opened 2022-06-23 16:14 UTC by AllanZhengYP

### Issue
Issue number, if available, prefixed with "#"

### Description
What does this implement/fix? Explain your changes.

### Testing
How was this change tested?

### Additional context
Add any other context about the PR here.

---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-06-23 17:55 UTC, AllanZhengYP commented
Currently the `@aws-sdk/lib-storage` unit test always takes 2 mins straight. I'm looking into the root cause.

2022-06-23 20:45 UTC, AllanZhengYP commented
I confirmed that process is not hang, jest spends minutes to compare the 5 MB buffer https://github.com/aws/aws-sdk-js-v3/blob/cbab94e901aec4650ab9e0eb19a4515e44d4ba62/lib/lib-storage/src/Upload.spec.ts#L233. I will replace it with comparing hash of them.

2022-06-24 14:42 UTC, trivikr requested changes
Requesting changes to block this PR, as CI has been failing.

2022-06-25 00:10 UTC, trivikr approved these changes

2022-06-25 00:23 UTC, merged