feat: support multiple error headers
aws/aws-sdk-js-v3 pull request #3852
Opened 2022-08-10 19:33 UTC by DanielBauman88

This change takes the first header value from x-amzn-errortype
if multiple headers are provided.

An example curl output for a response that this works for:
```
HTTP/2 401
date: Tue, 09 Aug 2022 21:24:20 GMT
content-type: application/json
content-length: 92
x-amzn-requestid: xxxx
access-control-allow-origin: *
x-amzn-errortype: UnauthorizedError
x-amzn-errortype: UnauthorizedException
x-amz-apigw-id: xxxx
x-amzn-trace-id: Root=xxxx
```
In this instance this code will select the first header value.

See related - https://github.com/awslabs/smithy/issues/1170

### Issue
Issue number, if available, prefixed with "#"

### Description
What does this implement/fix? Explain your changes.

### Testing
How was this change tested?

### Additional context
Add any other context about the PR here.

---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-09-02 18:19 UTC, AllanZhengYP approved these changes

2022-09-02 18:21 UTC, kuhe requested changes
[ ] run codegen for clients

I can do that and merge when able

2022-09-02 19:24 UTC, srchase approved these changes

2022-09-05 16:44 UTC, DanielBauman88 commented
> * [ ]  run codegen for clients
> 
> 
> I can do that and merge when able

Hey Kuhe, did you request changes with this comment? Trying to understand if I'm missing something in the ui.

2022-09-06 14:45 UTC, kuhe approved these changes

2022-09-06 15:29 UTC, merged