S3 middleware 200 exception fix and tests
aws/aws-sdk-js-v3 pull request #3874
Opened 2022-08-22 19:47 UTC by siddsriv

### Issue
#3856

### Description
Fixes failed requests always returning 400 as the response code.

### Testing
Added two unit tests in `throw-200-exceptions.spec.ts`

---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-08-23 18:14 UTC, trivikr commented
The failing tests are integration tests in S3. It looks like there's some issue with mocking in those tests.

```console
  1) Throw 200 response
       should throw if UploadPartCopy() return with 200 and empty payload:

      AssertionError: expected promise to be rejected with an error including 'S3 aborted request' but got 'UnknownError'
      + expected - actual

      -UnknownError
      +S3 aborted request
      
  

  2) Throw 200 response
       should throw if CompleteMultipartUpload() return with 200 and empty payload:

      AssertionError: expected promise to be rejected with an error including 'S3 aborted request' but got 'UnknownError'
      + expected - actual

      -UnknownError
      +S3 aborted request
      
```

2022-08-23 18:45 UTC, trivikr requested changes

2022-08-23 18:45 UTC, trivikr commented on packages/middleware-sdk-s3/src/throw-200-exceptions.spec.ts
> +  describe("exceptions for code < 200 and >= 300", () => {
nit: be explicit
```suggestion
  describe("exceptions for statusCode < 200 and >= 300", () => {
```

2022-08-23 18:45 UTC, trivikr commented on packages/middleware-sdk-s3/src/throw-200-exceptions.spec.ts
> +    it("throws an exception if code is less than 200", async () => {
Lot of code is shared between the two tests, where only statusCode is different.
You can use [it.each](https://jestjs.io/docs/api#testeachtablename-fn-timeout) for it as follows:

```js
it.each([199, 300])("throws for status code %d", async (statusCode) => {
```

2022-08-23 18:45 UTC, trivikr commented on packages/middleware-sdk-s3/src/throw-200-exceptions.spec.ts
> +    });
The middleware shouldn't throw an error when status code is <200 or >=300.

This code should be:
```suggestion
    const result = await handler({
        input: {},
        request: new HttpRequest({
          hostname: "s3.us-east-1.amazonaws.com",
        }),
      });
    expect(result.response).toBe(mockResponse);
```

Where:

```js
      mockNextHandler.mockReturnValue({
        response: mockResponse,
      });
```

2022-08-23 21:10 UTC, siddsriv commented
(force) push above -- that refactors the tests. Needs more work before PR.

2022-08-25 02:33 UTC, trivikr requested changes

2022-08-25 02:33 UTC, trivikr commented on yarn.lock
>  "@octokit/endpoint@^6.0.1":
Undo changes in yarn.lock, as this file doesn't need to be edited.

2022-08-25 02:33 UTC, trivikr commented on packages/middleware-sdk-s3/src/throw-200-exceptions.spec.ts
> +        // body: "",
Uncomment, and pass body with some content?
```suggestion
        headers: {},
        body: "body",
```

2022-08-29 20:16 UTC, AllanZhengYP approved these changes

2022-08-29 20:21 UTC, kuhe approved these changes

2022-09-06 14:53 UTC, trivikr approved these changes

2022-09-06 14:54 UTC, merged