feat(types): update identity types
aws/aws-sdk-js-v3 pull request #4189
Opened 2022-11-15 00:19 UTC by syall

### Issue
Issue number, if available, prefixed with "#"

### Description
What does this implement/fix? Explain your changes.

### Testing
How was this change tested?

### Additional context
Add any other context about the PR here.

---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-11-15 08:02 UTC, syall commented on packages/types/src/credentials.ts
>  export type CredentialProvider = Provider<Credentials>;
Should this be the following?

```suggestion
/**
 * @deprecated Use {@AwsCredentialIdentityProvider}
 */
export type CredentialProvider = IdentityProvider<Credentials>;
```

2022-11-15 08:02 UTC, syall commented on packages/types/src/token.ts
>  export type TokenProvider = Provider<Token>;
Should this be the following?

```suggestion
/**
 * @deprecated Use {@TokenIdentityProvider}
 */
export type TokenProvider = IdentityProvider<Token>;
```

2022-11-16 21:30 UTC, AndrewFossAWS approved these changes

2022-11-16 21:50 UTC, syall commented on packages/types/src/identity/Identity.ts
> +};
Does it matter if `IdentityProvider` is a type or an interface?

For reference, `Provider` is an interface: https://github.com/aws/aws-sdk-js-v3/blob/main/packages/types/src/util.ts#L34-L43.

2022-11-17 17:03 UTC, trivikr requested changes

2022-11-18 22:11 UTC, trivikr approved these changes

2022-11-18 22:11 UTC, merged