feat(module): add checksum interface
aws/aws-sdk-js-v3 pull request #4216
Opened 2022-11-21 17:56 UTC by AndrewFossAWS

### Description
Add checksum interface

### Testing
yarn build:all && yarn test:all

---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-11-21 19:13 UTC, syall requested changes

2022-11-21 19:13 UTC, syall commented on packages/types/src/checksum.ts
> +   * This is required by certain languages like Java.
Do we need this comment?

```suggestion
```

2022-11-21 19:13 UTC, syall commented on packages/types/src/checksum.ts
> +   * For the purpose of this document, we assume it's called synchronously.
Remove this comment.

2022-11-21 19:13 UTC, syall commented on packages/types/src/checksum.ts
> + * computing checksum.
Maybe document it for classes that implement this interface

```suggestion
 *
 * A class that implements this interface may accept an optional secret key in its
 * constructor while computing checksum value, when using HMAC. If provided,
 * this secret key would be used when computing checksum.
```

2022-11-21 20:03 UTC, syall approved these changes

2022-11-30 21:10 UTC, trivikr commented on packages/types/src/checksum.ts
> +  copy?: () => Checksum;
Use method syntax
```suggestion
  copy?(): Checksum;
```

2022-11-30 21:12 UTC, trivikr requested changes

2022-11-30 21:12 UTC, trivikr commented on packages/types/src/checksum.ts
> +  copy?: () => Checksum;
Use method syntax in interface
```suggestion
  copy?(): Checksum;
```

2022-11-30 21:12 UTC, trivikr commented on packages/types/src/checksum.ts
> +  digest: () => Promise<Uint8Array>;
Use method syntax in interface
```suggestion
  digest(): Promise<Uint8Array>;
```

2022-11-30 21:12 UTC, trivikr commented on packages/types/src/checksum.ts
> +  mark?: (readLimit: number) => void;
Use method syntax in interface
```suggestion
  mark?(readLimit: number): void;
```

2022-11-30 21:12 UTC, trivikr commented on packages/types/src/checksum.ts
> +  reset: () => void;
Use method syntax in interface
```suggestion
  reset(): void;
```

2022-11-30 21:31 UTC, trivikr requested changes

2022-11-30 21:31 UTC, trivikr commented on packages/types/src/crypto.ts
> + * @deprecated use {@link Checksum}
Add `import { Checksum } from "./checksum";` at the top of the file so that the type would be linked

2022-11-30 21:37 UTC, trivikr approved these changes

2022-11-30 21:41 UTC, merged