chore: add smoke test traits dep
aws/aws-sdk-js-v3 pull request #5664
Opened 2024-01-10 19:26 UTC by milesziemer

### Issue
Issue number, if available, prefixed with "#"

### Description
What does this implement/fix? Explain your changes.

Adds a dependency on smithy-smoke-test-traits in the sdk code gen package so aws service models that use the smokeTests trait won't fail to build because of unknown traits.

### Testing
How was this change tested?

Generated a client with a smoke test and confirmed there was no diff.

### Additional context
Add any other context about the PR here.

Adding the dependency in the code gen package since it's the models that need the dependency, not the code generator. When smoke tests are implemented in the generator, we can add the dep there.

### Checklist
- [ ] If you wrote E2E tests, are they resilient to concurrent I/O?
- [ ] If adding new public functions, did you add the `@public` tag and enable doc generation on the package?

---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-01-10 20:57 UTC, kuhe approved these changes

2024-01-10 21:13 UTC, syall approved these changes

2024-01-10 21:16 UTC, hpmellema requested changes
Should this be added to the same place as the other trait dependencies? 
https://github.com/aws/aws-sdk-js-v3/blob/main/codegen/smithy-aws-typescript-codegen/build.gradle.kts#L37

2024-01-10 22:40 UTC, milesziemer commented
> Should this be added to the same place as the other trait dependencies? https://github.com/aws/aws-sdk-js-v3/blob/main/codegen/smithy-aws-typescript-codegen/build.gradle.kts#L37

Since this is a model dependency right now, i.e. the code generator implementation isn't using it, we're just adding it as a dep where the models are loaded. If anything it is a little funky that the model dependencies would be available through the code generator implementation package.

2024-01-11 15:54 UTC, hpmellema approved these changes

2024-01-11 15:57 UTC, merged