fix(middleware-eventstream): lowercase headers more consistently
aws/aws-sdk-js-v3 pull request #6259
Opened 2024-07-08 18:41 UTC by kuhe

### Issue
Issue number, if available, prefixed with "#"

### Description
What does this implement/fix? Explain your changes.

### Testing
How was this change tested?

### Additional context
Add any other context about the PR here.

### Checklist
- [ ] If you wrote E2E tests, are they resilient to concurrent I/O?
- [ ] If adding new public functions, did you add the `@public` tag and enable doc generation on the package?

---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-07-08 18:46 UTC, siddsriv approved these changes

2024-07-09 14:19 UTC, trivikr requested changes

2024-07-09 14:19 UTC, trivikr commented on packages/middleware-websocket/src/middleware-websocket-endpoint.spec.ts
> +        "content-type": "application/vnd.amazon.eventstream",
This is original case to test removal of both cases
```suggestion
        "Content-Type": "application/vnd.amazon.eventstream",
```

2024-07-09 15:09 UTC, trivikr commented on packages/middleware-websocket/src/middleware-websocket-endpoint.spec.ts
> -      expect(processed.headers["Content-Type"]).toBeUndefined();
The removal of `"Content-Type"` needs to be checked

2024-07-09 15:28 UTC, trivikr approved these changes

2024-07-09 16:14 UTC, merged