feat(credential-providers): add custom credential chain helper
aws/aws-sdk-js-v3 pull request #6374
Opened 2024-08-09 20:38 UTC by kuhe

### Issue
Issue number, if available, prefixed with "#"

### Description
What does this implement/fix? Explain your changes.

### Testing
How was this change tested?

### Additional context
Add any other context about the PR here.

### Checklist
- [ ] If you wrote E2E tests, are they resilient to concurrent I/O?
- [ ] If adding new public functions, did you add the `@public` tag and enable doc generation on the package?

---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-08-09 20:50 UTC, siddsriv approved these changes

2024-08-09 21:00 UTC, trivikr requested changes

2024-08-09 21:00 UTC, trivikr commented on clients/client-s3/src/commands/GetObjectCommand.ts
> +GetObjectCommand.getEndpointParameterInstructions;
Is this added by mistake?

2024-08-12 14:33 UTC, trivikr commented on packages/credential-providers/README.md
> +  }),
Avoid cloning credentials in example?
```suggestion
  credentials: chain(fromEnv(), fromIni(), async () => {
    return myCredentialsFromSomewhereElse;
  }),
```

2024-08-12 14:33 UTC, trivikr commented on packages/credential-providers/src/customCredentialChain.ts
> +export const chain = (
Should we name this `customCredentialChain`, or something specific?

We already export a generic `chain` function from `property-provider`.

2024-08-12 14:33 UTC, trivikr commented on packages/credential-providers/src/customCredentialChain.ts
> +  -readonly [Property in keyof Type]: Type[Property];
Typo?
```suggestion
   readonly [Property in keyof Type]: Type[Property];
```

2024-08-12 15:24 UTC, kuhe commented on packages/credential-providers/src/customCredentialChain.ts
> + * });
this example should be edited. I think the following is better than inline map:

```ts
const init = { logger: console };

chain(fromEnv(init), fromIni(init));
```

2024-08-12 19:58 UTC, trivikr commented on packages/credential-providers/src/customCredentialChain.ts
> +export const createCredentialChain = (
Rename file to `createCredentialChain.ts`?

2024-08-12 20:01 UTC, trivikr approved these changes

2024-08-12 21:26 UTC, merged